### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Henry2o1o**

### CODE REVIEW

**Comment by Henry2o1o** [comment]
image

1 > What does that mean?

or >1?

**Comment by Henry2o1o** [comment]
1 <

**Comment by BurgerZ** [comment]
> is just the symbol to show you that you can press on alerts line to show more info :) I can remove it

**Comment by Henry2o1o** [comment]
as text?

en: tap here
de: hier tippen

or Button

**Comment by Henry2o1o** [comment]
Where is the sign (>)?

**Comment by Henry2o1o** [comment]
activity_main_clickable 
<-

**Comment by Henry2o1o** [comment]
and/or
activity_main_alert
Alarm: %1$d | tap here

**Comment by Henry2o1o** [comment]
img_20180514_121638

**Comment by Henry2o1o** [comment]
Works FINE 😃

**Pull request merged**
